### ISSUE TITLE
How can I calculate center of offset?

### ISSUE THREAD

**Issue by yustapps** [do9core/roulette#27]
Hi,

I want to roll to exact center when animation ends, but I don't know who to do that with offset. How can I do it ? My arrow looks weird. I attach screenshot (I am using example)

<img width="112" alt="image" src="https://github.com/do9core/roulette/assets/73885779/c4033b02-f8b1-483b-a317-cc0e2d2a4f9e">

Thank you so much.

**Comment by do9core** [comment]
The example is using a `Random` as offset generator to simulate real world case.

If you want to stop at exact center of a sector, set the `offset` [here](https://github.com/do9core/roulette/blob/1194967a36464049bcbc216d04884658fdec91cf/example/lib/main.dart#L175C9-L179C11) from `_random.nextDouble()` to `0.5` is enough.
